### ISSUE TITLE
Not working with multiple command parameters

### ISSUE THREAD

**Issue by rafaelmaeuer** [ufoscout/docker-compose-wait#22]
When starting a node app or a pm2 config file the usual docker command is:
```
CMD [ "node", "app.js" ]
//or
CMD [ "pm2-runtime", "app.yml" ]
```
When trying to run with docker-compose-wait:
```
CMD /wait && [ "pm2-runtime", "app.yml" ]
```
it fails with following error:
`/bin/sh: 1: [: pm2-runtime,: unexpected operator`

**Comment by ufoscout** [comment]
@rafaelmaeuer 
The syntax of the docker `CMD` instruction (see [the official docs](https://docs.docker.com/engine/reference/builder/#cmd) ) can only be one of the following two:
- CMD ["executable","param1","param2"]
- CMD command param1 param2

So, in your case, the issue is not in the `wait` executable but in the wrong syntax of your `CMD` command

**Comment by rafaelmaeuer** [comment]
that solved it - thank you very much for the hint
